# Generated by Django 4.2.20 on 2025-12-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_invitation_deleted_at_alter_invitation_created_at_and_more'),
    ]

    operations = [
    ]
