# Generated by Django 4.2.20 on 2025-11-30 15:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("educational_institution_type", models.CharField(max_length=255)),
                ("city_id", models.UUIDField()),
                ("university_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "teams",
            },
        ),
        migrations.CreateModel(
            name="UserTeam",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("has_permission_manage_users", models.BooleanField(default=False)),
                ("has_permission_manage_projects", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_teams",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_teams",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "user_teams",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("captain", "captain"),
                            ("vice-captain", "vice-captain"),
                            ("developer", "developer"),
                            ("designer", "designer"),
                            ("pm", "pm"),
                            ("pr", "pr"),
                            ("hr", "hr"),
                            ("business-adviser", "business-adviser"),
                            ("academic-adviser", "academic-adviser"),
                            ("marketer", "marketer"),
                            ("event-manager", "event-manager"),
                        ],
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="users.user",
                    ),
                ),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.AddConstraint(
            model_name="userteam",
            constraint=models.UniqueConstraint(
                fields=("user", "team"), name="unique_user_team_membership"
            ),
        ),
    ]
